name: Validate Mihomo Rules

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          sudo apt update
          sudo apt install yamllint -y

      - name: Validate YAML files
        run: |
          yamllint .
